-- ~/.hammerspoon/clipstack.lua
-- Gestionnaire de presse-papier EN PILE (historique empilé, browsable).
-- Copier empile ; ⌥⌘V ouvre une palette ; choisir un item le colle dans l'app active.
-- Texte + images, persistant (~100 items), skip auto des contenus sensibles (mots de passe).
-- Module autonome rechargeable à chaud ; chargé depuis init.lua : clipstack = require("clipstack")

local M = {}

-------------------------------------------------------------------------------
-- Config (tout est modifiable ici)

local HOME          = os.getenv("HOME")
local DIR           = HOME .. "/.hammerspoon/clipstack" -- données runtime (gitignoré)
local JSON          = DIR .. "/stack.json"
local LOG           = DIR .. "/clipstack.log"
local MAX           = 100          -- plafond d'items
local MAX_TEXT      = 1024 * 1024  -- 1 Mo : au-delà, texte non stocké
local PREVIEW_LEN   = 80           -- longueur max de l'aperçu affiché
local SAVE_DEBOUNCE = 0.5          -- s : écriture disque débouncée
local PASTE_DELAY   = 0.10         -- s : délai avant ⌘V (laisse le focus revenir)
local HOTKEY_MODS   = { "cmd", "alt" }
local HOTKEY_KEY    = "v"

-- Types de presse-papier à NE JAMAIS capturer (gestionnaires de mdp, champs sensibles)
local SENSITIVE_TYPES = {
  ["org.nspasteboard.ConcealedType"]     = true,
  ["org.nspasteboard.TransientType"]     = true,
  ["org.nspasteboard.AutoGeneratedType"] = true,
}

-------------------------------------------------------------------------------
-- État module

local stack      = {}    -- pile : index 1 = sommet (le plus récent)
local counter    = 0     -- compteur monotone pour nommer les fichiers image
local ignoreNext = false -- garde anti-boucle : ignore la prochaine capture (nos propres écritures)
local saveTimer  = nil
local panel      = nil   -- le webview du panneau (créé plus bas)
local outsideTap = nil   -- eventtap "clic en dehors" (actif quand le panneau est ouvert)

-------------------------------------------------------------------------------
-- Log discret (n'interrompt jamais)

local function logMsg(msg)
  local ok, f = pcall(io.open, LOG, "a")
  if ok and f then
    f:write(os.date("%Y-%m-%d %H:%M:%S ") .. tostring(msg) .. "\n")
    f:close()
  end
end

-------------------------------------------------------------------------------
-- Helpers purs

-- Hash FNV-1a 32 bits (Lua 5.4, entiers 64 bits + opérateurs bit-à-bit)
local function fnv1a(s)
  local hash = 2166136261
  for i = 1, #s do
    hash = hash ~ s:byte(i)
    hash = (hash * 16777619) & 0xFFFFFFFF
  end
  return string.format("%08x", hash)
end

-- Aperçu affichable : 1re ligne NON VIDE, espaces normalisés, tronquée.
local function previewOf(text)
  local stripped = text:gsub("^%s+", "")           -- ignore les blancs/retours de tête
  local first = stripped:match("^[^\n]*") or stripped -- 1re ligne réelle (plus la ligne vide)
  first = first:gsub("%s+", " "):gsub("%s+$", "")
  if #first > PREVIEW_LEN then first = first:sub(1, PREVIEW_LEN) .. "…" end
  if first == "" then first = "(espaces)" end        -- ne reste que pour un contenu 100% blanc
  return first
end

-- Le presse-papier est-il marqué sensible ? types = tableau d'UTI.
local function isSensitive(types)
  if type(types) ~= "table" then return false end
  for _, t in ipairs(types) do
    if SENSITIVE_TYPES[t] then return true end
  end
  return false
end

-- Clé de dédup d'une image : taille du fichier + empreinte d'un échantillon.
local function imageKey(path)
  local f = io.open(path, "rb")
  if not f then return nil end
  local size = f:seek("end") or 0
  f:seek("set", 0)
  local sample = f:read(8192) or ""
  f:close()
  return fnv1a(tostring(size) .. ":" .. sample)
end

-- Clé d'identité d'un item (pour dédup + remontée).
local function dupKey(item)
  if item.kind == "image" then return "I:" .. (item.key or item.file or "") end
  return "T:" .. (item.text or "")
end

-------------------------------------------------------------------------------
-- Stockage

local function ensureDir()
  if not hs.fs.attributes(DIR) then hs.fs.mkdir(DIR) end
end

local function doSave()
  saveTimer = nil
  local ok, encoded = pcall(hs.json.encode, { v = 1, counter = counter, items = stack }, true)
  if not ok then logMsg("encode JSON échoué: " .. tostring(encoded)); return end
  local f = io.open(JSON, "w")
  if not f then logMsg("écriture stack.json impossible"); return end
  local wok, werr = pcall(f.write, f, encoded)
  f:close()
  if not wok then logMsg("écriture stack.json échouée: " .. tostring(werr)) end
end

-- Écriture débouncée (évite de marteler le disque en rafale de copies).
local function save()
  if saveTimer then saveTimer:stop() end
  saveTimer = hs.timer.doAfter(SAVE_DEBOUNCE, doSave)
end

-- Éviction des plus vieux au-delà de MAX (+ suppression de leur image).
local function trim()
  while #stack > MAX do
    local ev = table.remove(stack) -- retire le dernier (le plus vieux)
    if ev and ev.file then os.remove(DIR .. "/" .. ev.file) end
  end
end

-- Cœur testable : insère item en tête, dédup+remontée, trim, persistance.
local function addItem(item)
  item.ts = hs.timer.secondsSinceEpoch()
  local k = dupKey(item)
  for i, it in ipairs(stack) do
    if dupKey(it) == k then
      table.remove(stack, i)
      -- doublon d'image via un NOUVEAU fichier : on jette le nouveau, on garde l'ancien
      if item.kind == "image" and item.file and it.file and item.file ~= it.file then
        os.remove(DIR .. "/" .. item.file)
        item = it
        item.ts = hs.timer.secondsSinceEpoch()
      end
      break
    end
  end
  table.insert(stack, 1, item)
  trim()
  save()
end

-- Chargement au démarrage + réparation (JSON corrompu → .bad) + nettoyage orphelins.
local function load()
  local f = io.open(JSON, "r")
  if not f then return end
  local raw = f:read("*a"); f:close()
  if not raw or raw == "" then return end

  local ok, data = pcall(hs.json.decode, raw)
  if not ok or type(data) ~= "table" or type(data.items) ~= "table" then
    os.rename(JSON, JSON .. ".bad")
    logMsg("stack.json corrompu → sauvegardé en .bad, repart d'une pile vide")
    return
  end

  counter = data.counter or 0

  -- Ne garde que les items valides (image dont le fichier existe encore).
  local kept = {}
  for _, it in ipairs(data.items) do
    if it.kind == "image" then
      if it.file and hs.fs.attributes(DIR .. "/" .. it.file) then kept[#kept + 1] = it end
    elseif it.text then
      kept[#kept + 1] = it
    end
  end
  stack = kept

  -- Supprime les fichiers image non référencés (orphelins).
  local referenced = {}
  for _, it in ipairs(stack) do if it.file then referenced[it.file] = true end end
  for file in hs.fs.dir(DIR) do
    if file:match("^img%-%d+%.png$") and not referenced[file] then
      os.remove(DIR .. "/" .. file)
    end
  end

  trim()
end

-------------------------------------------------------------------------------
-- API publique + debug

function M.count() return #stack end

-- Force l'écriture immédiate (annule le save débouncé en attente).
function M.flush()
  if saveTimer then saveTimer:stop(); saveTimer = nil end
  doSave()
end

function M.clear()
  for _, it in ipairs(stack) do
    if it.file then os.remove(DIR .. "/" .. it.file) end
  end
  stack = {}
  save()
end

-- Table de debug/validation (fonctions pures + injection sans passer par le presse-papier).
M._ = {
  previewOf   = previewOf,
  isSensitive = isSensitive,
  dupKey      = dupKey,
  stack       = function() return stack end,
  pushText    = function(t) addItem({ kind = "text", text = t, preview = previewOf(t) }) end,
}

-------------------------------------------------------------------------------
-- Capture (watcher)

local function onPasteboardChange()
  -- Garde anti-boucle : ignore nos propres écritures (voir Task 3 / collage).
  if ignoreNext then ignoreNext = false; return end

  -- Filtre sécurité : jamais les contenus sensibles.
  if isSensitive(hs.pasteboard.pasteboardTypes()) then return end

  -- Texte prioritaire.
  local txt = hs.pasteboard.readString()
  if txt and txt:match("%S") then
    if #txt > MAX_TEXT then return end -- garde-fou taille
    addItem({ kind = "text", text = txt, preview = previewOf(txt) })
    return
  end

  -- Sinon image.
  local img = hs.pasteboard.readImage()
  if img then
    counter = counter + 1
    local fname = string.format("img-%06d.png", counter)
    local fpath = DIR .. "/" .. fname
    if not img:saveToFile(fpath) then
      logMsg("saveToFile échoué: " .. fname)
      return
    end
    addItem({ kind = "image", file = fname, key = imageKey(fpath), preview = "Image" })
  end
  -- Ni texte ni image (ex. fichiers Finder) : ignoré (hors scope).
end

local pbWatcher = hs.pasteboard.watcher.new(onPasteboardChange)
pbWatcher:start()
M._watcher = pbWatcher -- conserve la référence (évite le GC du watcher)

-------------------------------------------------------------------------------
-- Panneau (hs.webview) + collage

local PANEL_FILE = os.getenv("HOME") .. "/.hammerspoon/clipstack-panel.html"

local function deleteItem(it)
  for i, x in ipairs(stack) do
    if x == it then
      table.remove(stack, i)
      if it.file then os.remove(DIR .. "/" .. it.file) end
      save()
      break
    end
  end
end

-- Bundle IDs de terminaux : Claude CLI y ingère les IMAGES via ⌃V (⌘V = collage texte du
-- terminal, ignoré par l'ingestion image). Ajoute d'autres terminaux ici si besoin.
local TERMINALS = {
  ["com.googlecode.iterm2"]  = true,
  ["com.apple.Terminal"]     = true,
  ["com.mitchellh.ghostty"]  = true,
  ["net.kovidgoyal.kitty"]   = true,
  ["io.alacritty"]           = true,
  ["com.github.wez.wezterm"] = true,
  ["dev.warp.Warp-Stable"]   = true,
}

-- App de devant capturée à l'OUVERTURE du panneau : c'est la cible du collage, et elle
-- détermine le raccourci (⌘V partout, sauf image dans un terminal → ⌃V pour Claude CLI).
local targetApp    = nil
local targetBundle = nil

-- Met l'item dans le presse-papier, le remonte en tête, puis colle dans l'app active.
local function pasteItem(it)
  ignoreNext = true -- notre écriture ne doit pas être re-capturée
  local ok
  if it.kind == "image" and it.file then
    local img = hs.image.imageFromPath(DIR .. "/" .. it.file)
    ok = img and hs.pasteboard.writeObjects(img)
  else
    ok = hs.pasteboard.setContents(it.text or "")
  end
  -- Écriture ratée (image introuvable ou write refusé) : on relâche le flag pour ne pas
  -- avaler la prochaine vraie copie, et on abandonne (ni remontée, ni collage).
  if not ok then ignoreNext = false; return end
  addItem(it) -- remonte l'item en tête (même référence → dédup l'attrape)
  -- Image dans un terminal (Claude CLI) → ⌃V ; sinon ⌘V (texte partout, images apps natives).
  local useCtrl = it.kind == "image" and targetBundle and TERMINALS[targetBundle]
  hs.timer.doAfter(PASTE_DELAY, function()
    if useCtrl then hs.eventtap.keyStroke({ "ctrl" }, "v")
    else hs.eventtap.keyStroke({ "cmd" }, "v") end
  end)
end

-- Dimensions PIXEL d'un PNG (lit l'en-tête IHDR : largeur/hauteur en big-endian).
local function pngDims(path)
  local f = io.open(path, "rb"); if not f then return nil end
  f:seek("set", 16); local b = f:read(8); f:close()
  if not b or #b < 8 then return nil end
  local function u32(s) return s:byte(1) * 16777216 + s:byte(2) * 65536 + s:byte(3) * 256 + s:byte(4) end
  return u32(b:sub(1, 4)), u32(b:sub(5, 8))
end

-- Construit le tableau d'items pour le JS (index stable = position dans stack).
local function itemsForJS()
  local out = {}
  for idx, it in ipairs(stack) do
    local e = { i = idx, kind = it.kind, preview = it.preview or "(vide)" }
    if it.kind == "image" and it.file then
      local w, h = pngDims(DIR .. "/" .. it.file)
      e.meta = (w and h) and string.format("%d × %d", w, h) or "image"
      local ok, uri = pcall(function()
        local img = hs.image.imageFromPath(DIR .. "/" .. it.file)
        return img and img:setSize({ w = 44, h = 44 }):encodeAsURLString() -- PNG par défaut
      end)
      if ok and uri then e.thumb = uri end
    else
      e.meta = tostring(utf8.len(it.text or "") or #(it.text or ""))
    end
    out[idx] = e
  end
  return out
end

-- Injecte la liste courante dans le panneau.
local function renderPanel()
  local ok, json = pcall(hs.json.encode, itemsForJS())
  if not ok then logMsg("encode items échoué: " .. tostring(json)); return end
  panel:evaluateJavaScript("CS.render(" .. json .. ")")
end

-- Pont retour JS -> Lua : actions du panneau.
local function onMessage(msg)
  local body = msg and msg.body or {}
  local action, i = body.action, body.i
  if action == "close" then
    panel:hide(); outsideTap:stop()
  elseif action == "paste" then
    local it = i and stack[i]
    panel:hide(); outsideTap:stop()
    if it then
      if targetApp then targetApp:activate() end
      pasteItem(it)
    end
  elseif action == "delete" then
    local it = i and stack[i]
    if it then deleteItem(it); renderPanel() end -- rafraîchit sans fermer
  end
end

-- Création du webview (une fois).
local usercontent = hs.webview.usercontent.new("clipstack")
usercontent:setCallback(onMessage)

local PANEL_HTML = ""
do
  local f = io.open(PANEL_FILE, "r")
  if f then PANEL_HTML = f:read("*a"); f:close() else logMsg("clipstack-panel.html introuvable") end
end

local PANEL_W, PANEL_H = 620, 460
panel = hs.webview.new({ x = 0, y = 0, w = PANEL_W, h = PANEL_H }, { developerExtrasEnabled = false }, usercontent)
-- Panneau non-activant : il ne vole pas l'app active et peut donc s'afficher
-- PAR-DESSUS un Space plein écran (Claude CLI dans iTerm fullscreen), comme Maccy/Paste.
panel:windowStyle({ "borderless", "nonactivating" })
panel:level(hs.drawing.windowLevels.modalPanel)
panel:allowTextEntry(true)
panel:closeOnEscape(true)
panel:transparent(true)
panel:deleteOnClose(false)
panel:html(PANEL_HTML)
-- Rejoint tous les Spaces (dont ceux en plein écran d'une autre app).
panel:behaviorAsLabels({ "canJoinAllSpaces", "fullScreenAuxiliary" })
M._panel = panel -- garde la référence en vie

-- Ferme le panneau si on clique en dehors de son cadre.
outsideTap = hs.eventtap.new({ hs.eventtap.event.types.leftMouseDown }, function(e)
  if not panel:isVisible() then return false end
  local p = hs.mouse.absolutePosition()
  local fr = panel:frame()
  local inside = p.x >= fr.x and p.x <= fr.x + fr.w and p.y >= fr.y and p.y <= fr.y + fr.h
  if not inside then panel:hide(); outsideTap:stop() end
  return false -- ne consomme pas le clic
end)

function M.toggle()
  if panel:isVisible() then panel:hide(); outsideTap:stop(); return end
  targetApp = hs.application.frontmostApplication()
  targetBundle = targetApp and targetApp:bundleID() or nil
  local sf = hs.screen.mainScreen():frame()
  panel:frame({ x = sf.x + (sf.w - PANEL_W) / 2, y = sf.y + (sf.h - PANEL_H) / 3, w = PANEL_W, h = PANEL_H })
  renderPanel()
  panel:show()
  panel:evaluateJavaScript("CS.focus()")
  outsideTap:start()
end

hs.hotkey.bind(HOTKEY_MODS, HOTKEY_KEY, M.toggle)

-------------------------------------------------------------------------------
-- Initialisation

ensureDir()
load()

-- Flush du save débouncé quand Hammerspoon quitte OU se recharge (sinon une copie
-- effectuée < SAVE_DEBOUNCE avant un reload serait perdue). Chaîne un callback existant.
local prevShutdown = hs.shutdownCallback
hs.shutdownCallback = function()
  if saveTimer then doSave() end
  if prevShutdown then prevShutdown() end
end

return M
