-- ~/.hammerspoon/clipstack.lua
-- Gestionnaire de presse-papier EN PILE (historique empilé, browsable).
-- Copier empile ; ⌥⌘V ouvre une palette ; choisir un item le colle dans l'app active.
-- Texte + images, persistant (~100 items), skip auto des contenus sensibles (mots de passe).
-- Module autonome rechargeable à chaud ; chargé depuis init.lua : clipstack = require("clipstack")

local M = {}

-------------------------------------------------------------------------------
-- Config (tout est modifiable ici)

local HOME          = os.getenv("HOME")
local DIR           = HOME .. "/.hammerspoon/clipstack" -- données runtime (gitignoré)
local JSON          = DIR .. "/stack.json"
local LOG           = DIR .. "/clipstack.log"
local MAX           = 100          -- plafond d'items
local MAX_TEXT      = 1024 * 1024  -- 1 Mo : au-delà, texte non stocké
local PREVIEW_LEN   = 80           -- longueur max de l'aperçu affiché
local SAVE_DEBOUNCE = 0.5          -- s : écriture disque débouncée
local PASTE_DELAY   = 0.10         -- s : délai avant ⌘V (laisse le focus revenir)
local HOTKEY_MODS   = { "cmd", "alt" }
local HOTKEY_KEY    = "v"

-- Types de presse-papier à NE JAMAIS capturer (gestionnaires de mdp, champs sensibles)
local SENSITIVE_TYPES = {
  ["org.nspasteboard.ConcealedType"]     = true,
  ["org.nspasteboard.TransientType"]     = true,
  ["org.nspasteboard.AutoGeneratedType"] = true,
}

-------------------------------------------------------------------------------
-- État module

local stack      = {}    -- pile : index 1 = sommet (le plus récent)
local counter    = 0     -- compteur monotone pour nommer les fichiers image
local ignoreNext = false -- garde anti-boucle : ignore la prochaine capture (nos propres écritures)
local saveTimer  = nil

-------------------------------------------------------------------------------
-- Log discret (n'interrompt jamais)

local function logMsg(msg)
  local ok, f = pcall(io.open, LOG, "a")
  if ok and f then
    f:write(os.date("%Y-%m-%d %H:%M:%S ") .. tostring(msg) .. "\n")
    f:close()
  end
end

-------------------------------------------------------------------------------
-- Helpers purs

-- Hash FNV-1a 32 bits (Lua 5.4, entiers 64 bits + opérateurs bit-à-bit)
local function fnv1a(s)
  local hash = 2166136261
  for i = 1, #s do
    hash = hash ~ s:byte(i)
    hash = (hash * 16777619) & 0xFFFFFFFF
  end
  return string.format("%08x", hash)
end

-- Aperçu affichable : 1re ligne, espaces normalisés, tronquée.
local function previewOf(text)
  local first = text:match("^[^\n]*") or text
  first = first:gsub("%s+", " "):gsub("^%s+", ""):gsub("%s+$", "")
  if #first > PREVIEW_LEN then first = first:sub(1, PREVIEW_LEN) .. "…" end
  if first == "" then first = "(espaces)" end
  return first
end

-- Le presse-papier est-il marqué sensible ? types = tableau d'UTI.
local function isSensitive(types)
  if type(types) ~= "table" then return false end
  for _, t in ipairs(types) do
    if SENSITIVE_TYPES[t] then return true end
  end
  return false
end

-- Clé de dédup d'une image : taille du fichier + empreinte d'un échantillon.
local function imageKey(path)
  local f = io.open(path, "rb")
  if not f then return nil end
  local size = f:seek("end") or 0
  f:seek("set", 0)
  local sample = f:read(8192) or ""
  f:close()
  return fnv1a(tostring(size) .. ":" .. sample)
end

-- Clé d'identité d'un item (pour dédup + remontée).
local function dupKey(item)
  if item.kind == "image" then return "I:" .. (item.key or item.file or "") end
  return "T:" .. (item.text or "")
end

-------------------------------------------------------------------------------
-- Stockage

local function ensureDir()
  if not hs.fs.attributes(DIR) then hs.fs.mkdir(DIR) end
end

local function doSave()
  saveTimer = nil
  local ok, encoded = pcall(hs.json.encode, { v = 1, counter = counter, items = stack }, true)
  if not ok then logMsg("encode JSON échoué: " .. tostring(encoded)); return end
  local f = io.open(JSON, "w")
  if not f then logMsg("écriture stack.json impossible"); return end
  local wok, werr = pcall(f.write, f, encoded)
  f:close()
  if not wok then logMsg("écriture stack.json échouée: " .. tostring(werr)) end
end

-- Écriture débouncée (évite de marteler le disque en rafale de copies).
local function save()
  if saveTimer then saveTimer:stop() end
  saveTimer = hs.timer.doAfter(SAVE_DEBOUNCE, doSave)
end

-- Éviction des plus vieux au-delà de MAX (+ suppression de leur image).
local function trim()
  while #stack > MAX do
    local ev = table.remove(stack) -- retire le dernier (le plus vieux)
    if ev and ev.file then os.remove(DIR .. "/" .. ev.file) end
  end
end

-- Cœur testable : insère item en tête, dédup+remontée, trim, persistance.
local function addItem(item)
  item.ts = hs.timer.secondsSinceEpoch()
  local k = dupKey(item)
  for i, it in ipairs(stack) do
    if dupKey(it) == k then
      table.remove(stack, i)
      -- doublon d'image via un NOUVEAU fichier : on jette le nouveau, on garde l'ancien
      if item.kind == "image" and item.file and it.file and item.file ~= it.file then
        os.remove(DIR .. "/" .. item.file)
        item = it
        item.ts = hs.timer.secondsSinceEpoch()
      end
      break
    end
  end
  table.insert(stack, 1, item)
  trim()
  save()
end

-- Chargement au démarrage + réparation (JSON corrompu → .bad) + nettoyage orphelins.
local function load()
  local f = io.open(JSON, "r")
  if not f then return end
  local raw = f:read("*a"); f:close()
  if not raw or raw == "" then return end

  local ok, data = pcall(hs.json.decode, raw)
  if not ok or type(data) ~= "table" or type(data.items) ~= "table" then
    os.rename(JSON, JSON .. ".bad")
    logMsg("stack.json corrompu → sauvegardé en .bad, repart d'une pile vide")
    return
  end

  counter = data.counter or 0

  -- Ne garde que les items valides (image dont le fichier existe encore).
  local kept = {}
  for _, it in ipairs(data.items) do
    if it.kind == "image" then
      if it.file and hs.fs.attributes(DIR .. "/" .. it.file) then kept[#kept + 1] = it end
    elseif it.text then
      kept[#kept + 1] = it
    end
  end
  stack = kept

  -- Supprime les fichiers image non référencés (orphelins).
  local referenced = {}
  for _, it in ipairs(stack) do if it.file then referenced[it.file] = true end end
  for file in hs.fs.dir(DIR) do
    if file:match("^img%-%d+%.png$") and not referenced[file] then
      os.remove(DIR .. "/" .. file)
    end
  end

  trim()
end

-------------------------------------------------------------------------------
-- API publique + debug

function M.count() return #stack end

-- Force l'écriture immédiate (annule le save débouncé en attente).
function M.flush()
  if saveTimer then saveTimer:stop(); saveTimer = nil end
  doSave()
end

function M.clear()
  for _, it in ipairs(stack) do
    if it.file then os.remove(DIR .. "/" .. it.file) end
  end
  stack = {}
  save()
end

-- Table de debug/validation (fonctions pures + injection sans passer par le presse-papier).
M._ = {
  previewOf   = previewOf,
  isSensitive = isSensitive,
  dupKey      = dupKey,
  stack       = function() return stack end,
  pushText    = function(t) addItem({ kind = "text", text = t, preview = previewOf(t) }) end,
}

-------------------------------------------------------------------------------
-- Capture (watcher)

local function onPasteboardChange()
  -- Garde anti-boucle : ignore nos propres écritures (voir Task 3 / collage).
  if ignoreNext then ignoreNext = false; return end

  -- Filtre sécurité : jamais les contenus sensibles.
  if isSensitive(hs.pasteboard.pasteboardTypes()) then return end

  -- Texte prioritaire.
  local txt = hs.pasteboard.readString()
  if txt and txt:match("%S") then
    if #txt > MAX_TEXT then return end -- garde-fou taille
    addItem({ kind = "text", text = txt, preview = previewOf(txt) })
    return
  end

  -- Sinon image.
  local img = hs.pasteboard.readImage()
  if img then
    counter = counter + 1
    local fname = string.format("img-%06d.png", counter)
    local fpath = DIR .. "/" .. fname
    if not img:saveToFile(fpath) then
      logMsg("saveToFile échoué: " .. fname)
      return
    end
    addItem({ kind = "image", file = fname, key = imageKey(fpath), preview = "🖼️ image" })
  end
  -- Ni texte ni image (ex. fichiers Finder) : ignoré (hors scope).
end

local pbWatcher = hs.pasteboard.watcher.new(onPasteboardChange)
pbWatcher:start()
M._watcher = pbWatcher -- conserve la référence (évite le GC du watcher)

-------------------------------------------------------------------------------
-- Popup (chooser) + collage

local function relTime(ts)
  local d = hs.timer.secondsSinceEpoch() - (ts or 0)
  if d < 60 then return "à l'instant"
  elseif d < 3600 then return string.format("il y a %d min", math.floor(d / 60))
  elseif d < 86400 then return string.format("il y a %d h", math.floor(d / 3600))
  else return string.format("il y a %d j", math.floor(d / 86400)) end
end

-- Construit les lignes du chooser depuis la pile (appelée à chaque ouverture/refresh).
local function buildChoices()
  local out = {}
  for _, it in ipairs(stack) do
    local choice = {
      text    = it.preview or "(vide)",
      subText = (it.kind == "image" and "Image" or "Texte") .. " · " .. relTime(it.ts),
      _item   = it, -- référence stable de l'item (résiste aux réordonnancements)
    }
    if it.kind == "image" and it.file then
      local img = hs.image.imageFromPath(DIR .. "/" .. it.file)
      if img then choice.image = img end
    end
    out[#out + 1] = choice
  end
  return out
end

local function deleteItem(it)
  for i, x in ipairs(stack) do
    if x == it then
      table.remove(stack, i)
      if it.file then os.remove(DIR .. "/" .. it.file) end
      save()
      break
    end
  end
end

-- Met l'item dans le presse-papier, le remonte en tête, puis colle (⌘V) dans l'app active.
local function pasteItem(it)
  ignoreNext = true -- notre écriture ne doit pas être re-capturée
  if it.kind == "image" and it.file then
    local img = hs.image.imageFromPath(DIR .. "/" .. it.file)
    if img then hs.pasteboard.writeObjects(img) else ignoreNext = false; return end
  else
    hs.pasteboard.setContents(it.text or "")
  end
  addItem(it) -- remonte l'item en tête (même référence → dédup l'attrape)
  hs.timer.doAfter(PASTE_DELAY, function()
    hs.eventtap.keyStroke({ "cmd" }, "v")
  end)
end

local function onChoice(choice)
  if not choice or not choice._item then return end -- Échap / clic dans le vide
  pasteItem(choice._item)
end

local chooser = hs.chooser.new(onChoice)
chooser:choices(buildChoices)
chooser:rightClickCallback(function(row)
  if not row or row < 1 then return end
  local c = chooser:selectedRowContents(row)
  if c and c._item then
    deleteItem(c._item)
    chooser:refreshChoicesCallback(true) -- true = ré-applique la requête de recherche courante
  end
end)

function M.toggle()
  if chooser:isVisible() then chooser:hide(); return end
  chooser:query("")
  chooser:refreshChoicesCallback()
  chooser:show()
end

hs.hotkey.bind(HOTKEY_MODS, HOTKEY_KEY, M.toggle)

-------------------------------------------------------------------------------
-- Initialisation

ensureDir()
load()

-- Flush du save débouncé quand Hammerspoon quitte OU se recharge (sinon une copie
-- effectuée < SAVE_DEBOUNCE avant un reload serait perdue). Chaîne un callback existant.
local prevShutdown = hs.shutdownCallback
hs.shutdownCallback = function()
  if saveTimer then doSave() end
  if prevShutdown then prevShutdown() end
end

return M
